
CREATE TABLE Utente (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE, 
    imgPath VARCHAR(255) DEFAULT 'default.jpg',
    isAdmin TINYINT(1) DEFAULT 0 NOT NULL,
    password CHAR(128) NOT NULL,
    CONSTRAINT fk_utente_admin CHECK (isAdmin IN (0, 1))
);

CREATE TABLE InfoConsegna (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    citta VARCHAR(255) NOT NULL,
    cap INT NOT NULL,
    via VARCHAR(255) NOT NULL,
    altro VARCHAR(255),
    destinatario VARCHAR(255) NOT NULL,
    idUtente BIGINT UNSIGNED NOT NULL,
    isDefault TINYINT(1) DEFAULT 0 NOT NULL,
    FOREIGN KEY (idUtente) REFERENCES Utente (id) ON DELETE CASCADE
);

CREATE TABLE Categoria (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE Prodotto (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descrizione VARCHAR(4096) NOT NULL,
    quantita INT UNSIGNED NOT NULL,
    prezzo DECIMAL(7, 2) NOT NULL,
    IVA ENUM('4', '10', '22') NOT NULL, 
    imgPath VARCHAR(255) NOT NULL,
    idCategoria BIGINT UNSIGNED NOT NULL,
    visibile TINYINT(1) DEFAULT 1 NOT NULL, -- serve per rimuovere dal catalogo
    FOREIGN KEY (idCategoria) REFERENCES Categoria (id)
);

CREATE TABLE Ordine (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUtente BIGINT UNSIGNED NOT NULL,
    infoConsegna BIGINT UNSIGNED NOT NULL,
    dataOrdine DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idUtente) REFERENCES Utente (id),
    FOREIGN KEY (infoConsegna) REFERENCES InfoConsegna (id)
);

CREATE TABLE Carrello (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUtente BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (idUtente) REFERENCES Utente (id) ON DELETE CASCADE
);

CREATE TABLE OrderItem (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL, 
    idProdotto BIGINT UNSIGNED NOT NULL,
    idOrdine BIGINT UNSIGNED NOT NULL,
    prezzo DECIMAL(7, 2) NOT NULL, 
    quantita INT NOT NULL,
    IVA ENUM('4', '10', '22') NOT NULL, 
    FOREIGN KEY (idOrdine) REFERENCES Ordine (id) ON DELETE CASCADE,
    FOREIGN KEY (idProdotto) REFERENCES Prodotto (id)
);

CREATE TABLE CartItem (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idProdotto BIGINT UNSIGNED NOT NULL,
    idCarrello BIGINT UNSIGNED NOT NULL,
    quantita BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (idCarrello) REFERENCES Carrello (id) ON DELETE CASCADE,
    FOREIGN KEY (idProdotto) REFERENCES Prodotto (id) ON DELETE CASCADE
);